#!/bin/bash
source ./requirements

TEST=`./myscript`
CORRECT=$'/home/vagrant/holbertonschool-checker/holbertonschool-sysadmin_devops/0x00-shell_basics/0-current_working_directory'
echo $TEST
echo $CORRECT

if [ "$STATE" = "0" ]; then
  if [ "$TEST" = "$CORRECT" ]; then
    echo "Success"
  else
    echo "Failed"
  fi
else
  echo "REQUIREMENTS NOT PASSED"
fi
