#!/bin/bash
source ./requirements

TEST=`./myscript`
CORRECT=`cd`

echo $TEST
echo $CORRECT

if [ "$STATE" = "0" ]; then
  if [ "$TEST" = "$CORRECT" ]; then
    echo "Success"
  else
    echo "Failed"
  fi
else
  echo "REQUIREMENTS NOT PASSED"
fi
